/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CpaStartupsRouteImport } from './routes/cpa-startups'
import { Route as CpaInternationalRouteImport } from './routes/cpa-international'
import { Route as CpaHerzliyaRouteImport } from './routes/cpa-herzliya'
import { Route as CpaFreelancersRouteImport } from './routes/cpa-freelancers'
import { Route as CpaForeignCompaniesRouteImport } from './routes/cpa-foreign-companies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaStartupsRoute = CpaStartupsRouteImport.update({
  id: '/cpa-startups',
  path: '/cpa-startups',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaInternationalRoute = CpaInternationalRouteImport.update({
  id: '/cpa-international',
  path: '/cpa-international',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaHerzliyaRoute = CpaHerzliyaRouteImport.update({
  id: '/cpa-herzliya',
  path: '/cpa-herzliya',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaFreelancersRoute = CpaFreelancersRouteImport.update({
  id: '/cpa-freelancers',
  path: '/cpa-freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaForeignCompaniesRoute = CpaForeignCompaniesRouteImport.update({
  id: '/cpa-foreign-companies',
  path: '/cpa-foreign-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cpa-foreign-companies': typeof CpaForeignCompaniesRoute
  '/cpa-freelancers': typeof CpaFreelancersRoute
  '/cpa-herzliya': typeof CpaHerzliyaRoute
  '/cpa-international': typeof CpaInternationalRoute
  '/cpa-startups': typeof CpaStartupsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cpa-foreign-companies': typeof CpaForeignCompaniesRoute
  '/cpa-freelancers': typeof CpaFreelancersRoute
  '/cpa-herzliya': typeof CpaHerzliyaRoute
  '/cpa-international': typeof CpaInternationalRoute
  '/cpa-startups': typeof CpaStartupsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cpa-foreign-companies': typeof CpaForeignCompaniesRoute
  '/cpa-freelancers': typeof CpaFreelancersRoute
  '/cpa-herzliya': typeof CpaHerzliyaRoute
  '/cpa-international': typeof CpaInternationalRoute
  '/cpa-startups': typeof CpaStartupsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cpa-foreign-companies'
    | '/cpa-freelancers'
    | '/cpa-herzliya'
    | '/cpa-international'
    | '/cpa-startups'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cpa-foreign-companies'
    | '/cpa-freelancers'
    | '/cpa-herzliya'
    | '/cpa-international'
    | '/cpa-startups'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cpa-foreign-companies'
    | '/cpa-freelancers'
    | '/cpa-herzliya'
    | '/cpa-international'
    | '/cpa-startups'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CpaForeignCompaniesRoute: typeof CpaForeignCompaniesRoute
  CpaFreelancersRoute: typeof CpaFreelancersRoute
  CpaHerzliyaRoute: typeof CpaHerzliyaRoute
  CpaInternationalRoute: typeof CpaInternationalRoute
  CpaStartupsRoute: typeof CpaStartupsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-startups': {
      id: '/cpa-startups'
      path: '/cpa-startups'
      fullPath: '/cpa-startups'
      preLoaderRoute: typeof CpaStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-international': {
      id: '/cpa-international'
      path: '/cpa-international'
      fullPath: '/cpa-international'
      preLoaderRoute: typeof CpaInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-herzliya': {
      id: '/cpa-herzliya'
      path: '/cpa-herzliya'
      fullPath: '/cpa-herzliya'
      preLoaderRoute: typeof CpaHerzliyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-freelancers': {
      id: '/cpa-freelancers'
      path: '/cpa-freelancers'
      fullPath: '/cpa-freelancers'
      preLoaderRoute: typeof CpaFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa-foreign-companies': {
      id: '/cpa-foreign-companies'
      path: '/cpa-foreign-companies'
      fullPath: '/cpa-foreign-companies'
      preLoaderRoute: typeof CpaForeignCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CpaForeignCompaniesRoute: CpaForeignCompaniesRoute,
  CpaFreelancersRoute: CpaFreelancersRoute,
  CpaHerzliyaRoute: CpaHerzliyaRoute,
  CpaInternationalRoute: CpaInternationalRoute,
  CpaStartupsRoute: CpaStartupsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
